// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiServerResource) DeepCopyInto(out *ApiServerResource) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
	in.ControllerSelector.DeepCopyInto(&out.ControllerSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiServerResource.
func (in *ApiServerResource) DeepCopy() *ApiServerResource {
	if in == nil {
		return nil
	}
	out := new(ApiServerResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceWatcher) DeepCopyInto(out *ResourceWatcher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceWatcher.
func (in *ResourceWatcher) DeepCopy() *ResourceWatcher {
	if in == nil {
		return nil
	}
	out := new(ResourceWatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceWatcher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceWatcherList) DeepCopyInto(out *ResourceWatcherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceWatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceWatcherList.
func (in *ResourceWatcherList) DeepCopy() *ResourceWatcherList {
	if in == nil {
		return nil
	}
	out := new(ResourceWatcherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceWatcherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceWatcherSpec) DeepCopyInto(out *ResourceWatcherSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ApiServerResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sink != nil {
		in, out := &in.Sink, &out.Sink
		*out = new(v1.ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceWatcherSpec.
func (in *ResourceWatcherSpec) DeepCopy() *ResourceWatcherSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceWatcherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceWatcherStatus) DeepCopyInto(out *ResourceWatcherStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceWatcherStatus.
func (in *ResourceWatcherStatus) DeepCopy() *ResourceWatcherStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceWatcherStatus)
	in.DeepCopyInto(out)
	return out
}
