kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-watcher
subjects:
- kind: ServiceAccount
  name: resource-watcher
  namespace: tekton-sources
roleRef:
  kind: ClusterRole
  name: resource-watcher
  apiGroup: rbac.authorization.k8s.io
