apiVersion: tekton.dev/v1alpha1
kind: ResourceWatcher
metadata:
  name: example-resourcewatcher
  namespace: tekton-sources
spec:
  serviceAccountName: "default"
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: knative-operator
    namespace: default
  resources:
    - apiVersion: operator.knative.dev/v1alpha1
      kind: KnativeEventing
  namespaces:
    - tekton-sources
  
