apiVersion: v1
kind: Pod
metadata:
  name: rss-site
  namespace: tekton-sources
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
