apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-with-taskspec-to-echo-good-morning
spec:
  pipelineSpec:
    tasks:
      - name: echo-good-morning
        taskSpec:
          metadata:
            labels:
              app: "example"
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "Good Morning!"
