apiVersion: tekton.dev/v1alpha1
kind: ResourceWatcher
metadata:
  name: example-resourcewatcher
  namespace: tekton-sources
spec:
  serviceAccountName: "default"
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display
    namespace: default
  resources:
    - apiVersion: v1
      kind: Pod
  
