apiVersion: tekton.dev/v1alpha1
kind: ResourceWatcher
metadata:
  name: example-resourcewatcher
  namespace: tekton-sources
spec:
  serviceAccountName: "default"
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: helloworld-go
    namespace: default
  resources:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
  namespaces:
    - tekton-sources
  
